### ISSUE TITLE
Non-trivial performance data breaks output

### ISSUE THREAD

**Issue by ahaerpfer** [arthru/python-mk-livestatus#2]
Any performance data output that contains multiple semicolon-separated values corrupts the returned dictionary.  For a minimal example take any host that has a *check-host-alive* check configured and try the following:

```
>>> q = s.hosts.columns('perf_data')
>>> pprint(q.call()[0])
{None: ['3000.000',
        '5000.000',
        '0',
        ' pl=0%',
        '80',
        '100',
        '',
        ' rtmax=28.500ms',
        '',
        '',
        '',
        ' rtmin=21.859ms',
        '',
        '',
        '',
        ''],
 'perf_data': 'rta=24.821ms'}
```

I.e. the first part of the output up until the first semicolon ends up in *perf_data*, all subsequent parts end up in an anonymous list.  If you do not filter for particular columns and instead do just a ``q = s.hosts`` the output looks even worse.

Not sure if this can be solved easily.  Livestatus here seems to mix it's own semicolons to separate columns with the semicolons present in the perfdata output without escaping the latter :-(

**Comment by ahaerpfer** [comment]
Hey, I've had a closer look at this issue and created a pull request that should fix this.  Kindly have a look.

**Comment by arthru** [comment]
Hi, I'll have a look later tonight...

**Comment by arthru** [comment]
That should be fixed in master branch.
